export { default as Header } from "./header";
export { default as Hero } from "./hero";
export { default as Services } from "./services";
export { default as About } from "./about";
export { default as Portfolio } from "./portfolio";
export { default as Testimonials } from "./testimonials";
export { default as CTA } from "./cta";
export { default as Footer } from "./footer";
export { default as SectionTitle } from "./sectionTitle";
